### ISSUE TITLE
Add Profile: 

### ISSUE THREAD

**Issue by nishant0708** [nishant0708/awesome-github-profiles#3]
paste a screenshot of your GitHub profile here
![Screenshot 2024-08-03 004715](https://github.com/user-attachments/assets/16e4589d-6516-4c5b-88b3-698e8b9c16d5)

enter category to label your profile
category:checking

then comment ``@all-contributors please add @<username> for review``

**Comment by nishant0708** [comment]
@all-contributors please add @Kratik1093 for review

**Comment by Kratik1093** [comment]
@all-contributors please add @22prachi for review
